hdfs:
  username: hdfs
  webhdfs:
    host: hadoop-master
    port: 50070

databases:
  default:
    alias: presto

  hive:
    jdbc_driver_class: org.apache.hive.jdbc.HiveDriver
    jdbc_url: jdbc:hive2://hadoop-master:10000
    jdbc_user: hdfs
    jdbc_password: na
    jdbc_pooling: false
    jdbc_jar: third-party-deps/build/libs/hive-jdbc-all-1.0.31-SNAPSHOT.jar
    table_manager_type: hive

  presto:
    jdbc_driver_class: com.facebook.presto.jdbc.PrestoDriver
    jdbc_url: jdbc:presto://presto-master:8080/hive/default
    jdbc_user: hdfs
    jdbc_password: na
    jdbc_pooling: false
    jdbc_jar: third-party-deps/build/libs/presto-jdbc-all.jar

tests:
  hdfs:
    path: /tempto

ssh_roles:
  td_express:
    host: ${TD_EXPRESS_HOST}
    port: 22
    user: root
    password: root
