hdfs:
  username: hdfs
  webhdfs:
    host: hadoop-master
    port: 50070

databases:
  default:
    alias: presto

  hive:
    jdbc_driver_class: org.apache.hive.jdbc.HiveDriver
    jdbc_url: jdbc:hive2://hadoop-master:10000
    jdbc_user: hdfs
    jdbc_password: na
    jdbc_pooling: false
    jdbc_jar: third-party-deps/build/libs/hive-jdbc-all.jar
    table_manager_type: hive

  presto:
    jdbc_driver_class: com.facebook.presto.jdbc.PrestoDriver
    jdbc_url: jdbc:presto://presto-master:8080/hive/default
    jdbc_user: hdfs
    jdbc_password: na
    jdbc_pooling: false
    jdbc_jar: third-party-deps/build/libs/presto-jdbc-all.jar

  # run psql instance with
  # docker run --name tempto-examples-psql -p 15432:5432 -e POSTGRES_USER=blah -e POSTGRES_PASSWORD=blah  -d postgres
  psql:
    jdbc_driver_class: org.postgresql.Driver
    jdbc_url: jdbc:postgresql://localhost:15432/postgres
    jdbc_user: blah
    jdbc_password: blah
    jdbc_pooling: true
    table_manager_type: jdbc

tests:
  hdfs:
    path: /tempto

ssh_roles:
  td_express:
    host: ${TD_EXPRESS_HOST}
    port: 22
    user: root
    password: root
