databases:
  presto:
    jdbc_url: jdbc:presto://localhost:8080/hive/default

ssh:
  identity: /Users/losipiuk/workspace/hfab/hfab/util/pkg_data/insecure_key.pem
  roles:
    host_by_password:
      user: test
      password: testtest
      host: master

    host_by_identity:
      host: master

blah:
  - x
  - y

DOCKER_MACHINE: 192.168.59.103
